### ISSUE TITLE
fatal error php dans le www/core/view.php

### ISSUE THREAD

**Issue by lumay** [Djaizansi/carsery#5]
Si on accède directement au lien /contact sans s'être connecté on a une fatal error, il faut surement rajouter un try catch a la ligne 22

**Comment by Djaizansi** [comment]
C'est déjà en place, il faut que dans ta fonction qui utilise la route /contact que tu entoures le tout avec un if(Session::estConnecte){

)else{
  throw new RouteException('Vous n'avez pas accès à cette page');
}
